example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_catalog

app_name = 'katalog'

urlpatterns = [
    path('', show_catalog, name='show_catalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_watchlist
from mywatchlist.views import show_xml
from mywatchlist.views import show_json
from mywatchlist.views import show_html

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_watchlist, name='show_watchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('html/', show_html, name='show_html'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist
from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import create_task
from todolist.views import status
from todolist.views import delete
from todolist.views import show_json
from todolist.views import create_task_AJAX

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create_task'),
    path('status/<int:id>/', status, name='status'),
    path('delete/<int:id>/', delete, name='delete'),
    path('json/', show_json, name='show_json'),
    path('add/',create_task_AJAX, name='create_task_AJAX'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.
class WatchList(models.Model):
    watched = models.CharField(max_length=50) #mendeskripsikan film tersebut sudah ditonton atau belum
    title = models.CharField(max_length=50) #mendeskripsikan judul film
    rating = models.IntegerField() #mendeskripsikan rating film dalam rentang 1 sampai dengan 5
    release_date = models.DateField() #mendeskripsikan kapan film dirilis
    review = models.TextField() #mendeskripsikan review untuk film tersebut

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) # Menghubungkan task dengan pengguna yang membuat task tersebut
    date = models.DateField(auto_now=True) # Mendeskripsikan tanggal pembuatan task
    title = models.CharField(max_length=100) # Mendeskripsikan judul task
    description = models.TextField() # Mendeskripsikan deskripsi task
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django.forms import ModelForm
from .models import Task

class CreateTask(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.
def show_catalog(request):
    data_item_katalog = CatalogItem.objects.all()
    context = {
        'nama' : 'Nadira Maysa Dyandra',
        'NPM' : '2106632232',
        'katalog' : data_item_katalog,
        }
    return render(request, 'katalog.html', context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import WatchList
from django.http import HttpResponse
from django.core import serializers

# Create your views here.
def show_watchlist(request):
    return render(request, "watchlist.html",)

def show_xml(request):
    data = WatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = WatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_html(request):
    data_watchlist = WatchList.objects.all()
    context = {
        'list_tontonan': data_watchlist,
        'nama': 'Nadira Maysa Dyandra',
        'NPM': '2106632232',
        }
    return render(request, "watchlist.html", context)

todolist/views.py
from datetime import date, datetime
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from .forms import CreateTask
from .models import Task
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data = Task.objects.filter(user = request.user)
    context = {
        'username': request.user,
        'todolist':data,
    }
    return render(request, "todolist.html", context)

@login_required(login_url='/todolist/login/')
def create_task(request):
    form = CreateTask()

    if request.method == "POST":
        form = CreateTask(request.POST)
        form.instance.user = request.user
        if form.is_valid():
            form.save()
            messages.success(request, 'Task telah berhasil dibuat!')
            return redirect('todolist:show_todolist')
    context = {'form':form}
    return render(request, "createtask.html", context)

@login_required(login_url='/todolist/login/')
@csrf_exempt
def status(request, id):
    if request.method == 'POST':
        task = get_object_or_404(Task, pk=id, user=request.user)
        task.is_finished = not task.is_finished
        task.save()

        return JsonResponse({'error': False})

@login_required(login_url='/todolist/login/')
@csrf_exempt
def delete(request, id):
    if request.method == 'POST':
        task = get_object_or_404(Task, pk=id, user=request.user)
        task.delete()

        return JsonResponse({'error': False})

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('todolist:show_todolist')
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    return redirect('todolist:login')

@login_required(login_url='/todolist/login/')
def show_json(request):
    data = Task.objects.filter(user=request.user).order_by('id')
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/todolist/login/')
@csrf_exempt
def create_task_AJAX(request):
    if request.method == "POST":
        user = request.user
        title = request.POST.get('title')
        description = request.POST.get('description')

        Task.objects.create(user=user,title=title, description=description)
    return JsonResponse({'error': False, 'msg':'Successful'})

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{NPM}}</p>

  <table>
      <tr>
          <th>Item Name</th>
          <th>Item Price</th>
          <th>Item Stock</th>
          <th>Rating</th>
          <th>Description</th>
          <th>Item URL</th>
      </tr>
      {% comment %} Add the data below this line {% endcomment %}
      {% for item in katalog %}
      <tr>
          <th>{{item.item_name}}</th>
          <th>{{item.item_price}}</th>
          <th>{{item.item_stock}}</th>
          <th>{{item.description}}</th>
          <th>{{item.rating}}</th>
          <th>{{item.item_url}}</th>
      </tr>
      {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/watchlist.html
{% extends 'base.html' %}

{% block content %}
<h1>Lab 2 Assignment PBP/PBD</h1>

<h5>Nama: </h5>
<b>{{nama}}</b>
<h5>Student ID: </h5>
<p>{{NPM}}</p>

<table>
    <tr>
        <th>Sudah/Belum</th>
        <th>Judul</th>
        <th>Rating</th>
        <th>Tanggal Rilis</th>
        <th>Review</th>
    </tr>
    {% comment %} Mencetak data ke dalam tabel {% endcomment %}
    {% for film in list_tontonan %}
    <tr>
        <th>{{film.watched}}</th>
        <th>{{film.title}}</th>
        <th>{{film.rating}}</th>
        <th>{{film.release_date}}</th>
        <th>{{film.review}}</th>
    </tr>
    {% endfor %}
</table>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Nadira Maysa Dyandra</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <!-- fonts google -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
  
  <!-- Iconscout CSS -->
  <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
  
  <!-- style -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>

</html>

todolist/templates/createtask.html
{% extends 'base.html' %}

{% block meta %}
<title>Create Task</title>
<style>
    *{
        padding: 0;
        margin: 0;
        box-sizing: border-box;
        font-family: 'Poppins', sans-serif;
    }
    body{
        display: flex;
        height: 100vh;
        justify-content: center;
        align-items: center;
        background: rgb(207, 228, 228);
    }
    .container{
        position: relative;
        max-width: 720px;
        width: 100%;
        background: white;
        border-radius: 10px;
        box-shadow: 12px 12px 12px grey;
        padding: 25px 30px;
    }
    .container .form{
        padding: 30px;
    }
    .title{
        position: relative;
        font-size: 27px;
        font-weight: 600;
    }
    .title::before{
        content: '';
        position: absolute;
        left: 0;
        bottom: 0;
        height: 3px;
        width: 30px;
        background-color: rgb(207, 228, 228);
        border-radius: 25px;
    }
    .btn{
        border: none;
        outline: none;
        height: 50px;
        width: 100%;
        background: black;
        color: white;
        border-radius: 5px;
        font-weight: bold;
    }
    .btn:hover{
        background: gray;
        border: none;
        color: black;
    }
    li{
        font-style: normal;
        font-weight: 400;
        font-size: 14px;
        line-height: 21px;
        color: red;
    }
</style>
{% endblock meta %}

{% block content %}
<div class="body">
    <div class="container">
        <span class="title">Membuat Task Baru</span>
        <form action="" method="post">
            {% csrf_token %}
            <div class="table-responsive">
                <table class="table table-borderless">
                    {{ form.as_table }}
                    <tr>
                        <td></td>
                        <td><input class="btn" type="submit" value="Buat Task"></td>
                    </tr>
                </table>
            </div>
        </form>
        <p class="my-2">Kembali ke halaman utama? <a href="{% url 'todolist:show_todolist' %}" class="text-decoration-none">Ya</a></p>
    </div>
</div>
{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<style>
    *{
        padding: 0;
        margin: 0;
        box-sizing: border-box;
        font-family: 'Poppins', sans-serif;
    }
    body{
        display: flex;
        height: 100vh;
        justify-content: center;
        align-items: center;
        background: rgb(207, 228, 228);
    }
    .container{
        position: relative;
        max-width: 600px;
        width: 100%;
        background: white;
        border-radius: 10px;
        box-shadow: 12px 12px 12px grey;
        padding: 25px 30px;
    }
    .container .form{
        padding: 30px;
    }
    .container .form .title{
        position: relative;
        font-size: 27px;
        font-weight: 600;

    }
    .form .title::before{
        content: '';
        position: absolute;
        left: 0;
        bottom: 0;
        height: 3px;
        width: 30px;
        background-color: rgb(207, 228, 228);
        border-radius: 25px;
    }
    .form .input-field{
        position: relative;
        height: 50px;
        width: 100%;
        margin-top: 30px;
    }
    .input-field input{
        position: absolute;
        height: 100%;
        width: 100%;
        padding: 0 35px;
        border: none;
        outline: none;
        font-size: 16px;
        border-bottom: 2px solid  rgb(207, 228, 228);
        border-top: 2px solid transparent;
    }
    .input-field i{
        position: absolute;
        top: 50%;
        left: 0;
        transform: translateY(-50%);
        color: black;
        font-size: 23px;
    }
    .btn{
        border: none;
        outline: none;
        height: 50px;
        width: 100%;
        background: black;
        color: white;
        border-radius: 5px;
        font-weight: bold;
    }
    .btn:hover{
        background: gray;
        border: none;
        color: black;
    }
    h4{
        font-style: normal;
        font-weight: 400;
        font-size: 16px;
        line-height: 24px;
        color: black;
    }
    p{
        font-style: normal;
        font-weight: 400;
        font-size: 14px;
        line-height: 21px;
        color: black;
    }
    .list-group-item{
        position: relative;
        font-style: normal;
        font-weight: 400;
        font-size: 14px;
        line-height: 21px;
        color: red;
        border: none;
    }
</style>
{% endblock meta %}

{% block content %}
<body>
    <div class="container">
        <div class="form login">
            <span class="title">Login</span>
            <form method="POST" action="">
                {% csrf_token %}
                <div class="input-field">
                    <input type="text" name="username" placeholder="Username" class="form-control">
                    <i class="uil uil-user"></i>
                </div>
                <div class="input-field">
                    <input type="password" name="password" placeholder="Password" class="form-control">
                    <i class="uil uil-lock"></i>
                </div>
                <div class="input-field">
                    <input class="btn login_btn" type="submit" value="Login">
                </div>
                {% if messages %}
                <ul class="list-group">
                    {% for message in messages %}
                    <li class="list-group-item">{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                <p class="my-2">Belum memiliki akun? <a href="{% url 'todolist:register' %}" class="text-decoration-none">Sign in disini</a></p>
            </form>
        </div>
    </div>
</body>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<style>
    *{
        padding: 0;
        margin: 0;
        box-sizing: border-box;
        font-family: 'Poppins', sans-serif;
    }
    body{
        display: flex;
        height: 100vh;
        justify-content: center;
        align-items: center;
        background: rgb(207, 228, 228);
    }
    .container{
        position: relative;
        max-width: 1080px;
        width: 100%;
        background: white;
        border-radius: 10px;
        box-shadow: 12px 12px 12px grey;
        padding: 25px 30px;
    }
    .container .form{
        padding: 30px;
    }
    .title{
        position: relative;
        font-size: 27px;
        font-weight: 600;
    }
    .title::before{
        content: '';
        position: absolute;
        left: 0;
        bottom: 0;
        height: 3px;
        width: 30px;
        background-color: rgb(207, 228, 228);
        border-radius: 25px;
    }
    .btn{
        border: none;
        outline: none;
        height: 50px;
        width: 100%;
        background: black;
        color: white;
        border-radius: 5px;
        font-weight: bold;
    }
    .btn:hover{
        background: gray;
        border: none;
        color: black;
    }
    li{
        font-style: normal;
        font-weight: 400;
        font-size: 14px;
        line-height: 21px;
        color: red;
    }
</style>
{% endblock meta %}

{% block content %}
<body>
    <div class="container">
        <div class="login">
            <span class="title">Formulir Registrasi</span>
            <form method="POST">
                {% csrf_token %}
                <div class="table-responsive">
                    <table class="table table-borderless"> 
                        {{ form.as_table }}
                        <tr>
                            <td></td>
                            <td><input class="btn" type="submit" name="submit" value="Daftar" /></td>
                        </tr>
                    </table>
                </div>
                <p class="my-2">Kembali ke halaman login? <a href="{% url 'todolist:login' %}" class="text-decoration-none">Ya</a></p>
            </form>
            {% if messages %}
                <ul class="list-group">
                    {% for message in messages %}
                    <li class="list-group-item">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
</body>
{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}
{% block meta %}
<style>
    *{
        padding: 0;
        margin: 0;
        box-sizing: border-box;
        font-family: 'Poppins', sans-serif;
    }
    body{
        display: flex;
        height: 100%;
        justify-content: center;
        align-items: center;
        background: rgb(207, 228, 228);
    }
    .container{
        position: relative;
        width: 100%;
        max-width: 2040px;
        background: white;
        border-radius: 10px;
        box-shadow: 12px 12px 12px grey;
        padding: 20px 30px;
    }
    .row{
        padding-top: 20px;
        padding-bottom: 20px;
    }
    .card{
        background: rgb(235, 235, 178);
        width: 100%;
        height: 100%;
        display: flex;
        justify-content: space-between;
        flex-direction: column;
    }
    .card:hover{
        background:  rgb(207, 228, 228);
    }
    .btn-1{
        position: relative;
        border: none;
        outline: none;
        height: 50px;
        width: 200px;
        background: black;
        border-radius: 10px;
        font-weight: bold;
    }
    .btn{
        border: none;
        outline: none;
        height: 50px;
        width: 200px;
        background: rgb(191, 185, 185);
        border-radius: 10px;
        font-weight: bold;
    }
    .button{
        border: none;
        outline: none;
        background: none;
    }
    .a1{
        border: none;
        outline: none;
        height: 50px;
        width: 200px;
        font-size: 14px;
        background: none;
        border-radius: 5px;
        font-weight: bold;
        color: white;
        text-decoration: none;
    }
    .a2{
        border: none;
        outline: none;
        height: 50px;
        width: 200px;
        background: none;
        border-radius: 5px;
        font-weight: bold;
        color: black;
        text-decoration: none;
    }
    h1{
        position: relative;
        font-size: 40px;
        font-weight: 600;
    }
    h2{
        margin-top: 10px;
        position: relative;
        font-style: normal;
        font-weight: bold;
        font-size: 25px;
        line-height: 27px;
        color: black;
        margin-left: 3px;
        margin-right: 3px;
    }
    h3{
        font-style: normal;
        font-weight: 400;
        font-size: 16px;
        line-height: 24px;
        color: black;
        margin-left: 3px;
        margin-right: 3px;
    }
    p{
        font-style: normal;
        font-weight: 500;
        font-size: 18px;
        line-height: 21px;
        color: black;
        margin-left: 3px;
        margin-right: 3px;
    }
    .list-group-item.satu{
        background: rgb(207, 241, 209);
    }
    .list-group-item.dua{
        background: rgb(237, 195, 195);
    }
</style>
{% endblock meta %}

{% block content %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<body>
    <section class="p-5">
        <div class="container">
            <h1>Halo {{user}}!</h1>
            <div class="d-grid gap-2 d-md-block">
                <button class="btn-1"><a href="{% url 'todolist:create_task' %}" class="a1">Create New Task</a></button>
                <button class="btn-1"><a href="{% url 'todolist:logout' %}" class="a1">Logout</a></button>
                <!-- Button trigger modal -->
                <button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Task</button>    
            </div>
            
            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Create Task</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="POST" action="">
                            {% csrf_token %}
                            <div class="mt-4">
                                <label for="Title">Title</label>
                            </div>
                            <input id="title-controller" type="text" name="title" placeholder="Title" required class="form-control">
                            <div class="mt-4">
                                <label for="description">Description</label>
                            </div>
                            <textarea id="description-controller" name="description" placeholder="Description" cols="30" rows="10" class="form-control" required></textarea>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button id="save-task" type="submit" class="btn btn-primary" value="Submit" onclick="">Save changes</button>
                            </div>
                        </form>
                    </div>
                </div>
                </div>
            </div>
            <!-- card  -->
            <div id="todos-container" class="row text-center g-4">
                <!--
                {% for todo in todolist %}
                <div class="col-md-4">
                    <div class="card">
                        <h2 class="card-title">{{todo.title}}</h2>
                        <h3 class="card-date">{{todo.date}}</h3>
                        <p class="card-text">{{todo.description}}</p>
                        {% if todo.is_finished %}
                        <h3>Status: Selesai</h3>
                        {% else %}
                        <h3>Status: Belum Selesai</h3>
                        {% endif %}                        
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item satu">
                                <a href="{% url 'todolist:status' todo.id %}" class="a2">Change Status</a>
                            </li>
                            <li class="list-group-item dua">
                                <a href="{% url 'todolist:delete' todo.id %}" class="a2">Delete Task</a>
                            </li>
                          </ul>
                    </div>
                </div>
                {% endfor %} -->
            </div>
        </div>
    </section>
</body>

<script>
    function update(pk) {
        $.post({
            url: `status/${pk}/`,
            type: 'post',
            data: {},
            success: showTodos
        })
    }

    function deleteTask(pk) {
        $.post({
            url: `delete/${pk}/`,
            type: 'post',
            data: {},
            success: showTodos
        })
    }

    function createTask() {
        $.post({
            url: `add/`,
            type: 'post',
            data: {
                'title': $('#title-controller').val(),
                'description': $('#description-controller').val(),
            },
            success: showTodos
        })
    }
    $(`#save-task`).attr('onclick', `createTask()`);

    function showTodos() {
        $.get(
            './json',
            function (data) {
                $('#todos-container').empty();
                for (let i = 0; i < data.length; i++) {
                    $('#todos-container').append(
                        `<div  class="col-md-4">
                            <div class="card">
                                <h2 class="card-title">${data[i].fields.title}</h2>
                                <h3 class="card-date">${data[i].fields.date}</h3>
                                <p class="card-text">${data[i].fields.description}</p>
                                <p id="todo-mark-${i}" class="card-text"></p>
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item satu">
                                        <button type="button" onclick="" id="status-button-${i}" class="button">Change Status</button>
                                    </li>
                                    <li class="list-group-item dua">
                                        <button type="button" onclick="" id="delete-button-${i}" class="button">Delete Task</button>
                                    </li>
                                </ul>
                            </div>
                        </div>`
                    )
                    if (data[i].fields.is_finished) {
                        $(`#todo-mark-${i}`).addClass('text-green-500').text('Selesai');
                    } else {
                        $(`#todo-mark-${i}`).addClass('text-red-600').text('Belum Selesai');
                    }
                    $(`#status-button-${i}`).attr('onclick', `update(${data[i].pk})`);
                    $(`#delete-button-${i}`).attr('onclick', `deleteTask(${data[i].pk})`)
                }
            }
        )
    }

    showTodos();
</script>

{% endblock content %}